language: node_js

node_js:
  - "6.17.0"	# Latest 6.x series LTS
  - "8.15.1"	# Latest 8.x series LTS
  - "10.15.3"	# Latest 10.x series LTS
  - "11.12.0"	# Latest released to date

before_install:
  - npm i -g npm --upgrade
  - npm i -g mocha

script:
  - npm test
  - npm run lint
